//go:build !windows

package main

import (
	"bytes"
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"testing/fstest"

	regsqlite "github.com/partite-ai/particles/registry/sqlite"
)

func TestShimScript_Content(t *testing.T) {
	got := shimScript(linkSpec{
		path:        "/usr/local/bin/gh",
		particleBin: "/opt/particle/particle",
		target:      "github-tools@1.2.0",
	})
	for _, want := range []string{
		"#!/bin/sh\n",
		"# generated by `particle link` -> particle run github-tools@1.2.0",
		"exec '/opt/particle/particle' run 'github-tools@1.2.0' \"$@\"\n",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("script missing %q in:\n%s", want, got)
		}
	}
	if strings.Contains(got, "--db") {
		t.Errorf("script should not mention --db when none was set:\n%s", got)
	}
}

func TestShimScript_WithDB(t *testing.T) {
	got := shimScript(linkSpec{
		particleBin: "/opt/particle",
		target:      "demo",
		dbPath:      "/var/lib/particle/state.db",
	})
	want := "exec '/opt/particle' run --db '/var/lib/particle/state.db' 'demo' \"$@\"\n"
	if !strings.Contains(got, want) {
		t.Errorf("script missing %q in:\n%s", want, got)
	}
}

func TestShSingleQuote_EscapesEmbeddedQuote(t *testing.T) {
	// A path with a single quote must round-trip as one shell word.
	got := shSingleQuote(`/weird/o'brien/particle`)
	want := `'/weird/o'\''brien/particle'`
	if got != want {
		t.Errorf("shSingleQuote = %q, want %q", got, want)
	}
}

func TestWriteLink_RefusesOverwriteWithoutForce(t *testing.T) {
	path := filepath.Join(t.TempDir(), "gh")
	if err := os.WriteFile(path, []byte("existing"), 0o644); err != nil {
		t.Fatal(err)
	}
	spec := linkSpec{path: path, particleBin: "/opt/particle", target: "demo"}

	if _, err := writeLink(spec, false); err == nil {
		t.Fatal("expected error overwriting existing file without --force")
	}
	if data, _ := os.ReadFile(path); string(data) != "existing" {
		t.Errorf("file was modified despite refusal: %q", data)
	}
	if _, err := writeLink(spec, true); err != nil {
		t.Fatalf("--force overwrite failed: %v", err)
	}
	if data, _ := os.ReadFile(path); !strings.HasPrefix(string(data), "#!/bin/sh") {
		t.Errorf("forced overwrite didn't write the shim: %q", data)
	}
}

func TestWriteLink_SetsExecutableBit(t *testing.T) {
	path := filepath.Join(t.TempDir(), "gh")
	if _, err := writeLink(linkSpec{path: path, particleBin: "/opt/particle", target: "demo"}, false); err != nil {
		t.Fatal(err)
	}
	info, err := os.Stat(path)
	if err != nil {
		t.Fatal(err)
	}
	if info.Mode().Perm()&0o111 == 0 {
		t.Errorf("shim not executable: mode %v", info.Mode())
	}
}

// TestWriteLink_ExecForwardsArgs runs the generated shim against a
// stub standing in for the particle binary, proving exec + "$@"
// forwarding works end to end: the stub must receive
// `run <target> <user-args...>` with word boundaries preserved.
func TestWriteLink_ExecForwardsArgs(t *testing.T) {
	dir := t.TempDir()
	argsFile := filepath.Join(dir, "args.txt")
	stub := filepath.Join(dir, "fake-particle")
	stubSrc := "#!/bin/sh\nfor a in \"$@\"; do printf '%s\\n' \"$a\"; done > \"" + argsFile + "\"\n"
	if err := os.WriteFile(stub, []byte(stubSrc), 0o755); err != nil {
		t.Fatal(err)
	}

	shim := filepath.Join(dir, "gh")
	if _, err := writeLink(linkSpec{path: shim, particleBin: stub, target: "github-tools"}, false); err != nil {
		t.Fatal(err)
	}

	cmd := exec.Command(shim, "list-issues", "--repo", "octo/hi there")
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("run shim: %v\n%s", err, out)
	}
	got, err := os.ReadFile(argsFile)
	if err != nil {
		t.Fatal(err)
	}
	want := "run\ngithub-tools\nlist-issues\n--repo\nocto/hi there\n"
	if string(got) != want {
		t.Errorf("stub received:\n%q\nwant:\n%q", got, want)
	}
}

// TestLink_CommandHappyPath drives the cobra command against a
// registry seeded with a minimal entry (no wasm needed — link never
// boots the particle, it only resolves it).
func TestLink_CommandHappyPath(t *testing.T) {
	ctx := context.Background()
	dir := t.TempDir()
	dbPath := filepath.Join(dir, "state.db")
	seedParticle(t, ctx, dbPath, "demo", "0.1.0")

	linkPath := filepath.Join(dir, "demo-link")
	out := runRoot(t, ctx, "link", "demo", linkPath, "--db", dbPath)
	if !strings.Contains(out, "linked "+linkPath+" -> particle run demo") {
		t.Errorf("unexpected link output: %q", out)
	}
	info, err := os.Stat(linkPath)
	if err != nil {
		t.Fatalf("link not created: %v", err)
	}
	if info.Mode().Perm()&0o111 == 0 {
		t.Errorf("link not executable: mode %v", info.Mode())
	}
	data, err := os.ReadFile(linkPath)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(string(data), "#!/bin/sh") {
		t.Errorf("link is not a shim: %q", data)
	}
}

func TestLink_UnregisteredParticleErrors(t *testing.T) {
	ctx := context.Background()
	dir := t.TempDir()
	dbPath := filepath.Join(dir, "state.db")
	// Empty registry: linking a missing particle must fail at link time.
	seedParticle(t, ctx, dbPath, "other", "0.1.0")

	root, _ := newRootCmd()
	root.SetArgs([]string{"link", "nope", filepath.Join(dir, "x"), "--db", dbPath})
	var buf bytes.Buffer
	root.SetOut(&buf)
	root.SetErr(&buf)
	if err := root.ExecuteContext(ctx); err == nil {
		t.Fatalf("expected error linking unregistered particle; output: %q", buf.String())
	}
	if _, err := os.Stat(filepath.Join(dir, "x")); !os.IsNotExist(err) {
		t.Error("link file should not be created when the particle doesn't resolve")
	}
}

func seedParticle(t *testing.T, ctx context.Context, dbPath, name, version string) {
	t.Helper()
	if _, err := resolveDBPath(dbPath); err != nil {
		t.Fatal(err)
	}
	db, err := openStateDB(dbPath)
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()
	reg, err := regsqlite.New(ctx, db)
	if err != nil {
		t.Fatal(err)
	}
	if err := reg.Put(ctx, name, version, fstest.MapFS{}); err != nil {
		t.Fatal(err)
	}
}

func runRoot(t *testing.T, ctx context.Context, args ...string) string {
	t.Helper()
	root, _ := newRootCmd()
	root.SetArgs(args)
	var buf bytes.Buffer
	root.SetOut(&buf)
	root.SetErr(&buf)
	if err := root.ExecuteContext(ctx); err != nil {
		t.Fatalf("root %v: %v\noutput: %s", args, err, buf.String())
	}
	return buf.String()
}
