//go:build !windows

package main

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"strings"
)

// writeLink writes a POSIX sh shim to spec.path. The shim execs the
// particle binary so signals and the exit code pass straight through,
// and forwards its arguments verbatim via "$@". Returns the path
// written (unchanged on Unix).
func writeLink(spec linkSpec, force bool) (string, error) {
	flag := os.O_CREATE | os.O_WRONLY | os.O_TRUNC
	if !force {
		flag |= os.O_EXCL
	}
	f, err := os.OpenFile(spec.path, flag, 0o755)
	if err != nil {
		if errors.Is(err, fs.ErrExist) {
			return "", fmt.Errorf("%s already exists (use --force to overwrite)", spec.path)
		}
		return "", fmt.Errorf("create link: %w", err)
	}
	if _, err := f.WriteString(shimScript(spec)); err != nil {
		f.Close()
		return "", fmt.Errorf("write link: %w", err)
	}
	if err := f.Close(); err != nil {
		return "", fmt.Errorf("write link: %w", err)
	}
	// O_TRUNC reuses an existing file's mode under --force, and the
	// create mode is masked by umask, so set the exec bits explicitly.
	if err := os.Chmod(spec.path, 0o755); err != nil {
		return "", fmt.Errorf("chmod link: %w", err)
	}
	return spec.path, nil
}

// shimScript renders the sh shim. The literals we control (binary
// path, db path, target) are single-quoted so a space or shell
// metacharacter in a path can't be re-expanded; "$@" stays
// double-quoted, the canonical forward-all-arguments idiom.
func shimScript(spec linkSpec) string {
	var b strings.Builder
	b.WriteString("#!/bin/sh\n")
	fmt.Fprintf(&b, "# generated by `particle link` -> particle run %s\n", spec.target)
	b.WriteString("exec ")
	b.WriteString(shSingleQuote(spec.particleBin))
	b.WriteString(" run")
	if spec.dbPath != "" {
		b.WriteString(" --db ")
		b.WriteString(shSingleQuote(spec.dbPath))
	}
	b.WriteByte(' ')
	b.WriteString(shSingleQuote(spec.target))
	b.WriteString(` "$@"` + "\n")
	return b.String()
}

// shSingleQuote wraps s in single quotes so the result is a single
// shell word with no expansion. An embedded single quote is escaped
// by closing the quote, emitting a backslash-escaped quote, and
// reopening — the standard POSIX-sh idiom.
func shSingleQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}
