"""
Particle Python runtime — the module componentize-py freezes into
particle-python-runtime.wasm.

Companion to components/js-runtime/src/runtime.ts: same outward contract
(tools.list-tools / tools.call-tool / health.ping), same "one image,
many particles" model. The user's Particlefile.py is *not* visible at
componentize-py build time — it lives on the wasi:filesystem preopen
the host mounts at /particle/bundle.py, and we load it through
importlib.machinery.SourceFileLoader on first invocation.

The frozen-stdlib import block below decides what's available to
user code without a build-time deps phase. componentize-py freezes
everything reachable from the entry module into the wasm; what we
don't import here costs a build-time pip step to add.
"""

# -- frozen stdlib (everything reachable from here goes in the wasm) --

import abc                         # noqa: F401
import asyncio                     # noqa: F401
import base64                      # noqa: F401
import collections                 # noqa: F401
import collections.abc             # noqa: F401
import contextlib                  # noqa: F401
import copy                        # noqa: F401
import dataclasses                 # noqa: F401
import datetime                    # noqa: F401
import decimal                     # noqa: F401
import enum                        # noqa: F401
import functools                   # noqa: F401
import hashlib                     # noqa: F401
import hmac                        # noqa: F401
import html                        # noqa: F401
import importlib
import importlib.machinery
import importlib.util
import inspect                     # noqa: F401
import io                          # noqa: F401
import itertools                   # noqa: F401
import json
import math                        # noqa: F401
import operator                    # noqa: F401
import os
import re                          # noqa: F401
import secrets                     # noqa: F401
import string                      # noqa: F401
import struct                      # noqa: F401
import sys
import textwrap                    # noqa: F401
import time                        # noqa: F401
import traceback
import types                       # noqa: F401
import typing                      # noqa: F401
import urllib.parse                # noqa: F401
import urllib.request              # noqa: F401  (urllib monkey-patch lives in particle.http)
import uuid                        # noqa: F401

# -- WIT bindings (generated by `componentize-py bindings .`) --

import wit_world  # noqa: F401
from wit_world.exports import Tools as ToolsProtocol
from wit_world.exports import Health as HealthProtocol
from wit_world.exports import Manifest as ManifestProtocol
from wit_world.exports.tools import (
    ToolDef,
    ToolError_NotFound,
    ToolError_HandlerError,
)
from wit_world.exports.health import (
    PingResult,
    Status,
    HealthError_NotImplemented,
    HealthError_HandlerError,
)
from wit_world.exports.manifest import (
    ManifestError_BundleLoadError,
    ManifestError_InvalidManifest,
    ParticleManifest,
    RuntimeKind,
    CapabilitySet,
    HttpCapability,
    CredentialEntry,
    CredentialMethodEntry,
    CredentialMethod_Basic,
    CredentialMethod_Oauth2,
    CredentialMethod_Apikey,
    CredentialMethod_SigningKey,
    CredentialMethod_Raw,
    Oauth2Method,
    Oauth2Flow,
    ApikeyMethod,
    ApikeyLocation,
    ApikeyLocationKind,
    SigningKeyMethod,
    SigningAlgorithm,
    ToolEntry,
)
from componentize_py_types import Err

# Import the particle helper package for its side effects (urllib
# monkey-patch). The user-visible API is `import particle.http` etc.
# from inside the user's bundle.py — same module, same names.
import particle  # noqa: F401


# -- user-bundle loader --------------------------------------------------

_USER_MODULE_PATH = "/particle/bundle.py"
_USER_MODULE_DIR = os.path.dirname(_USER_MODULE_PATH)
# Where the build pipeline unpacks resolved wheels. Mounted by the
# host as part of the particle's FS — same wasi:filesystem preopen
# that exposes bundle.py. Adding it to sys.path lets user code do
# `import httpx` (or any other resolved pure-Python dep) at runtime.
_DEPS_SITE_PACKAGES = "/particle/_deps/site-packages"

# Sticky cache so each tool call doesn't reparse/re-exec the bundle.
# Errors stick too: a malformed bundle gets the same error every call
# rather than retrying — matches the JS runtime's behavior.
_user_module: object | None = None
_load_error: BaseException | None = None


def _load_user_module():
    """Load /particle/bundle.py through importlib.SourceFileLoader.

    SourceFileLoader bypasses sys.path entirely (we point it directly
    at the file). We still mutate sys.path so user code doing its own
    `import sibling` works for multi-file particles.
    """
    global _user_module, _load_error
    if _user_module is not None:
        return _user_module
    if _load_error is not None:
        raise _load_error

    try:
        if _USER_MODULE_DIR not in sys.path:
            sys.path.insert(0, _USER_MODULE_DIR)
        # _deps/site-packages contains the build-pipeline-resolved
        # wheels (httpx, pyjwt, …). Only added when the directory
        # actually exists — particles with no third-party deps never
        # ship the _deps tree, and a non-existent sys.path entry is
        # harmless but noise in tracebacks.
        if os.path.isdir(_DEPS_SITE_PACKAGES) and _DEPS_SITE_PACKAGES not in sys.path:
            sys.path.insert(0, _DEPS_SITE_PACKAGES)
        loader = importlib.machinery.SourceFileLoader("bundle", _USER_MODULE_PATH)
        spec = importlib.util.spec_from_loader("bundle", loader)
        if spec is None:
            raise RuntimeError(f"could not build module spec for {_USER_MODULE_PATH}")
        module = importlib.util.module_from_spec(spec)
        loader.exec_module(module)
    except BaseException as e:
        _load_error = e
        raise

    _user_module = module
    return module


def _get_particle() -> dict:
    """Return the module-level `particle` dict from the user's bundle.

    Mirrors the JS DSL's default export: the user writes
    `particle = {"name": ..., "tools": {...}, "ping": ...}` at module
    scope. Plain dict (not dataclass / Pydantic) so JSON-Schema input
    schemas stay plain dicts and tool handlers stay plain callables.
    """
    mod = _load_user_module()
    obj = getattr(mod, "particle", None)
    if obj is None:
        raise RuntimeError("bundle.py must define a module-level `particle` dict")
    if not isinstance(obj, dict):
        raise RuntimeError(
            f"bundle.py `particle` must be a dict, got {type(obj).__name__}"
        )
    return obj


def _describe(e: BaseException) -> str:
    """Render an exception for the handler-error WIT variant.

    Matches components/js-runtime/src/runtime.ts:describeThrown — the
    full stack goes to stderr, only a one-line summary into the WIT
    error payload.
    """
    msg = str(e) or repr(e)
    return f"{type(e).__name__}: {msg}"


def _log_traceback(e: BaseException) -> None:
    """Send the traceback to wasi:cli/stderr (design doc §6: full
    stack on stderr, message only in the WIT result).
    """
    traceback.print_exception(type(e), e, e.__traceback__, file=sys.stderr)


# -- WIT exports ---------------------------------------------------------


class Tools(ToolsProtocol):
    """Implements `particle:runtime/tools`."""

    def list_tools(self) -> list[ToolDef]:
        try:
            particle = _get_particle()
        except BaseException as e:
            _log_traceback(e)
            # list-tools has no error variant — surface the load
            # failure as a recognizable tool row so the host gets a
            # readable diagnostic rather than a wasm trap.
            return [ToolDef(
                name="__particle_load_error__",
                description=_describe(e),
                input_schema_json="{}",
            )]

        out: list[ToolDef] = []
        for name, defn in (particle.get("tools") or {}).items():
            description = defn.get("description") or ""
            schema = defn.get("inputSchema") or {"type": "object"}
            out.append(ToolDef(
                name=name,
                description=description,
                input_schema_json=json.dumps(schema),
            ))
        return out

    def call_tool(self, name: str, arguments_json: str) -> str:
        try:
            particle = _get_particle()
        except BaseException as e:
            _log_traceback(e)
            raise Err(ToolError_HandlerError(_describe(e)))

        defn = (particle.get("tools") or {}).get(name)
        if defn is None:
            raise Err(ToolError_NotFound())

        handler = defn.get("handler")
        if not callable(handler):
            raise Err(ToolError_HandlerError(
                f"tool {name!r} has no callable handler"
            ))

        # Args are pre-validated host-side against the tool's input
        # schema (design doc §6 "Argument validation: host-side
        # only"). Trust them.
        try:
            args = json.loads(arguments_json)
        except Exception as e:
            raise Err(ToolError_HandlerError(
                f"argument JSON parse: {_describe(e)}"
            ))

        try:
            result = handler(args)
            if asyncio.iscoroutine(result):
                result = asyncio.run(result)
        except BaseException as e:
            _log_traceback(e)
            raise Err(ToolError_HandlerError(_describe(e)))

        try:
            return json.dumps(result)
        except Exception as e:
            raise Err(ToolError_HandlerError(
                f"result is not JSON-serializable: {_describe(e)}"
            ))


class Manifest(ManifestProtocol):
    """Implements `particle:runtime/manifest` — see the WIT for rationale.

    Called by the build pipeline (Phase 5) and by any host that wants
    to learn what credentials/tools the particle exposes. Module-
    scope `particle.*` helper calls aren't supported: under introspect
    the host wires trap stores so those surface as "not allowed
    during get-manifest" errors.
    """

    def get_manifest(self) -> ParticleManifest:
        try:
            particle = _get_particle()
        except BaseException as e:
            _log_traceback(e)
            raise Err(ManifestError_BundleLoadError(_describe(e)))

        try:
            return _build_manifest_record(particle)
        except BaseException as e:
            _log_traceback(e)
            raise Err(ManifestError_InvalidManifest(_describe(e)))


# Shared validation messages + small lookup tables. Surface as
# module-level constants so the corresponding JS runtime code can be
# kept in lock-step by diffing against this file.

_OAUTH2_FLOW_MAP = {
    "authorization-code":      Oauth2Flow.AUTHORIZATION_CODE,
    "authorization-code-pkce": Oauth2Flow.AUTHORIZATION_CODE_PKCE,
    "device-code":             Oauth2Flow.DEVICE_CODE,
}
_APIKEY_LOCATION_KIND_MAP = {
    "header":      ApikeyLocationKind.HEADER,
    "auth-scheme": ApikeyLocationKind.AUTH_SCHEME,
    "query-param": ApikeyLocationKind.QUERY_PARAM,
}
_SIGNING_ALGORITHM_MAP = {
    "hmac-sha256": SigningAlgorithm.HMAC_SHA256,
    "hmac-sha512": SigningAlgorithm.HMAC_SHA512,
}


def _build_manifest_record(particle: dict) -> ParticleManifest:
    """Coerce the user's `particle` dict into the typed WIT manifest
    record — a tree of componentize-py dataclass instances the WIT
    canonical ABI knows how to lift across the host boundary.
    """
    name = particle.get("name")
    if not isinstance(name, str) or not name:
        raise ValueError("particle.name must be a non-empty string")

    description = particle.get("description", "")
    if not isinstance(description, str):
        raise ValueError("particle.description must be a string")

    version = particle.get("version")
    if not isinstance(version, str) or not version:
        raise ValueError("particle.version must be a non-empty string")

    if "runtime" in particle:
        rt = particle["runtime"]
        if rt not in ("python",):
            raise ValueError(
                f'particle.runtime must be "python" for a .py particle, got {rt!r}'
            )

    raw_caps = particle.get("capabilities", {})
    if not isinstance(raw_caps, dict):
        raise ValueError("particle.capabilities must be a dict")
    capabilities = _build_capability_set(raw_caps)

    raw_creds = particle.get("credentials") or {}
    if not isinstance(raw_creds, dict):
        raise ValueError("particle.credentials must be a dict")
    credentials = _build_credentials(raw_creds)

    raw_tools = particle.get("tools")
    if not isinstance(raw_tools, dict):
        raise ValueError("particle.tools must be a dict")
    tools = _build_tools(raw_tools)

    # Python particles always run on the Python runtime — emit the
    # field unconditionally so the host's dispatch picks the right
    # wasm.
    return ParticleManifest(
        name=name,
        description=description,
        version=version,
        runtime=RuntimeKind.PYTHON,
        capabilities=capabilities,
        credentials=credentials,
        tools=tools,
    )


def _build_capability_set(raw: dict) -> CapabilitySet:
    http = raw.get("http")
    if http is None:
        return CapabilitySet(http=None)
    if not isinstance(http, dict):
        raise ValueError("capabilities.http must be a dict")
    allowed = http.get("allowedHosts") or []
    if not isinstance(allowed, list) or not all(isinstance(h, str) for h in allowed):
        raise ValueError("capabilities.http.allowedHosts must be a list of strings")
    return CapabilitySet(http=HttpCapability(allowed_hosts=list(allowed)))


def _build_credentials(raw: dict) -> list:
    out = []
    for cname, cred in raw.items():
        if not isinstance(cred, dict):
            raise ValueError(f"credentials.{cname} must be a dict")
        hosts = cred.get("hosts") or []
        if not isinstance(hosts, list) or not all(isinstance(h, str) for h in hosts):
            raise ValueError(f"credentials.{cname}.hosts must be a list of strings")
        methods_raw = cred.get("methods") or {}
        if not isinstance(methods_raw, dict):
            raise ValueError(f"credentials.{cname}.methods must be a dict")
        methods = []
        for mname, method in methods_raw.items():
            methods.append(CredentialMethodEntry(
                name=mname,
                description=method.get("description", "") if isinstance(method, dict) else "",
                method=_build_credential_method(cname, mname, method),
            ))
        out.append(CredentialEntry(
            name=cname,
            hosts=list(hosts),
            required=bool(cred.get("required", False)),
            methods=methods,
        ))
    return out


def _build_credential_method(cname: str, mname: str, method) -> "CredentialMethod":
    if not isinstance(method, dict):
        raise ValueError(f"credentials.{cname}.methods.{mname} must be a dict")
    kind = method.get("type")
    if kind == "basic":
        return CredentialMethod_Basic()
    if kind == "raw":
        return CredentialMethod_Raw()
    if kind == "oauth2":
        flows = method.get("flows") or []
        try:
            mapped_flows = [_OAUTH2_FLOW_MAP[f] for f in flows]
        except KeyError as e:
            raise ValueError(f"credentials.{cname}.methods.{mname}: unknown OAuth2 flow {e}")
        return CredentialMethod_Oauth2(value=Oauth2Method(
            flows=mapped_flows,
            scopes=list(method.get("scopes") or []),
            authorization_url=method.get("authorizationUrl", ""),
            token_url=method.get("tokenUrl", ""),
            device_auth_url=method.get("deviceAuthUrl", ""),
        ))
    if kind == "apikey":
        loc = method.get("location")
        if loc is None:
            return CredentialMethod_Apikey(value=ApikeyMethod(location=None))
        if not isinstance(loc, dict):
            raise ValueError(f"credentials.{cname}.methods.{mname}.location must be a dict")
        try:
            kind_enum = _APIKEY_LOCATION_KIND_MAP[loc.get("kind", "")]
        except KeyError:
            raise ValueError(f"credentials.{cname}.methods.{mname}.location.kind {loc.get('kind')!r} not recognized")
        return CredentialMethod_Apikey(value=ApikeyMethod(location=ApikeyLocation(
            kind=kind_enum,
            name=loc.get("name"),
            scheme=loc.get("scheme"),
        )))
    if kind == "signing-key":
        try:
            alg = _SIGNING_ALGORITHM_MAP[method.get("algorithm", "")]
        except KeyError:
            raise ValueError(f"credentials.{cname}.methods.{mname}.algorithm {method.get('algorithm')!r} not recognized")
        return CredentialMethod_SigningKey(value=SigningKeyMethod(algorithm=alg))
    raise ValueError(f"credentials.{cname}.methods.{mname}.type {kind!r} not recognized")


def _build_tools(raw: dict) -> list:
    out = []
    for tname, defn in raw.items():
        if not isinstance(defn, dict):
            raise ValueError(f"tools.{tname} must be a dict")
        tdesc = defn.get("description")
        if not isinstance(tdesc, str):
            raise ValueError(f"tools.{tname}.description must be a string")
        schema = defn.get("inputSchema")
        if not isinstance(schema, dict):
            raise ValueError(f"tools.{tname}.inputSchema must be a dict")
        handler = defn.get("handler")
        if not callable(handler):
            raise ValueError(f"tools.{tname}.handler must be callable")
        out.append(ToolEntry(
            name=tname,
            description=tdesc,
            input_schema_json=json.dumps(schema),
        ))
    return out


class Health(HealthProtocol):
    """Implements `particle:runtime/health`."""

    def ping(self) -> PingResult:
        try:
            particle = _get_particle()
        except BaseException as e:
            _log_traceback(e)
            raise Err(HealthError_HandlerError(_describe(e)))

        ping_fn = particle.get("ping")
        if not callable(ping_fn):
            raise Err(HealthError_NotImplemented())

        try:
            result = ping_fn()
            if asyncio.iscoroutine(result):
                result = asyncio.run(result)
        except BaseException as e:
            _log_traceback(e)
            raise Err(HealthError_HandlerError(_describe(e)))

        return _to_ping_result(result)


def _to_ping_result(payload: object) -> PingResult:
    """Coerce a user-returned payload into a PingResult.

    Accepts either a PingResult instance or the dict form
    `{"status": "ok|degraded|unhealthy", "message"?: str, "details"?: any}`.
    Dict form lets handlers stay free of WIT-binding imports.
    """
    if isinstance(payload, PingResult):
        return payload
    if not isinstance(payload, dict):
        raise RuntimeError(
            f"ping must return a dict or PingResult, got {type(payload).__name__}"
        )
    status_map = {
        "ok": Status.OK,
        "degraded": Status.DEGRADED,
        "unhealthy": Status.UNHEALTHY,
    }
    status_str = payload.get("status", "ok")
    if status_str not in status_map:
        raise RuntimeError(f"ping returned unknown status {status_str!r}")

    message = payload.get("message")
    details = payload.get("details")
    if details is not None and not isinstance(details, str):
        # Match the WIT contract: details is JSON, encoded as string.
        details = json.dumps(details)
    return PingResult(
        status=status_map[status_str],
        message=message,
        details=details,
    )
