"""
Particle Python runtime — the module componentize-py freezes into
particle-python-runtime.wasm.

Implements the `particle:runtime` WIT contract (tools.list-tools /
tools.call-tool / health.ping / manifest.get-manifest) on top of a
"one image, many particles" model: the user's Particlefile.py is
*not* visible at componentize-py build time — it lives on the
wasi:filesystem preopen the host mounts at /particle/bundle.py, and
we load it through importlib.machinery.SourceFileLoader on first
invocation.

The frozen-stdlib import block below decides what's available to
user code without a build-time deps phase. componentize-py freezes
everything reachable from the entry module into the wasm; what we
don't import here costs a build-time pip step to add.
"""

# -- frozen stdlib (everything reachable from here goes in the wasm) --

import abc                         # noqa: F401
import asyncio                     # noqa: F401
import base64                      # noqa: F401
import collections                 # noqa: F401
import collections.abc             # noqa: F401
import contextlib                  # noqa: F401
import copy                        # noqa: F401
import dataclasses                 # noqa: F401
import datetime                    # noqa: F401
import decimal                     # noqa: F401
import email                       # noqa: F401  (urllib3 / http.client header parsing)
import email.message               # noqa: F401
import encodings                   # noqa: F401
import encodings.idna              # noqa: F401  (requests host-encoding for non-ASCII)
import encodings.utf_8             # noqa: F401
import encodings.latin_1           # noqa: F401
import enum                        # noqa: F401
import errno                       # noqa: F401  (urllib3 retry classification)
import functools                   # noqa: F401
import hashlib                     # noqa: F401
import hmac                        # noqa: F401
import html                        # noqa: F401
import http                        # noqa: F401
import http.client                 # noqa: F401  (urllib3.connection imports HTTPException etc.)
import http.cookiejar              # noqa: F401  (httpx imports this; broadly useful)
import http.cookies                # noqa: F401
import importlib
import importlib.abc                 # noqa: F401  (custom loaders / finders)
import importlib.machinery
import importlib.metadata            # noqa: F401  (urllib3 reads its installed version)
import importlib.readers             # noqa: F401
import importlib.resources           # noqa: F401  (requests / certifi look up bundled CA bundle)
import importlib.resources._adapters # noqa: F401
import importlib.resources._common   # noqa: F401
import importlib.resources.abc       # noqa: F401
import importlib.resources.readers   # noqa: F401  (transitively used by requests)
import importlib.resources.simple    # noqa: F401
import importlib.util
import inspect                     # noqa: F401
import io                          # noqa: F401
import itertools                   # noqa: F401
import json
import logging                     # noqa: F401  (urllib3 adds a NullHandler at import)
import math                        # noqa: F401
import mimetypes                   # noqa: F401  (urllib3 / requests multipart)
import operator                    # noqa: F401
import os
import queue                       # noqa: F401  (urllib3.connectionpool uses queue.LifoQueue)
import random                      # noqa: F401  (urllib3 retry jitter)
import re                          # noqa: F401
import secrets                     # noqa: F401
import socket                      # noqa: F401  (overridden by particle._socket_guard)
import string                      # noqa: F401
import struct                      # noqa: F401
import sys
import textwrap                    # noqa: F401
import threading                   # noqa: F401  (urllib3 pool locking)
import time                        # noqa: F401
import traceback
import types                       # noqa: F401
import typing                      # noqa: F401
import urllib.parse                # noqa: F401
import urllib.request              # noqa: F401  (urllib monkey-patch lives in particle.http)
import uuid                        # noqa: F401
import warnings                    # noqa: F401  (urllib3 warns on TLS / deprecations)
import weakref                     # noqa: F401  (urllib3 PoolManager keeps weak refs)
import zlib                        # noqa: F401  (urllib3 / requests decompress)

# -- WIT bindings (generated by `componentize-py bindings .`) --

import wit_world  # noqa: F401
from wit_world.exports import Tools as ToolsProtocol
from wit_world.exports import Health as HealthProtocol
from wit_world.exports import Manifest as ManifestProtocol
# Each interface gets its own `ErrorDetail` (inlined per-interface in
# the WIT so types-only `use` doesn't require a separately-imported
# `diagnostics` interface on the world). The structure is identical
# across all three; only the Python class identity differs.
from wit_world.exports.tools import (
    ToolDef,
    ToolError_NotFound,
    ToolError_HandlerError,
    ErrorDetail as ToolErrorDetail,
)
from wit_world.exports.health import (
    PingResult,
    Status,
    HealthError_NotImplemented,
    HealthError_HandlerError,
    ErrorDetail as HealthErrorDetail,
)
from wit_world.exports.manifest import (
    ManifestError_BundleLoadError,
    ManifestError_InvalidManifest,
    ParticleManifest,
    CapabilitySet,
    HttpCapability,
    CredentialEntry,
    CredentialMethodEntry,
    CredentialMethod_Basic,
    CredentialMethod_Oauth2,
    CredentialMethod_Apikey,
    CredentialMethod_SigningKey,
    CredentialMethod_Raw,
    Oauth2Method,
    Oauth2Flow,
    ApikeyMethod,
    ApikeyLocation,
    ApikeyLocationKind,
    SigningKeyMethod,
    SigningAlgorithm,
    ToolEntry,
    ErrorDetail as ManifestErrorDetail,
)
from componentize_py_types import Err

# Import the particle helper package for its side effects (urllib
# monkey-patch) and to access the user-facing manifest types. The
# user-visible API is `import particle.http`, `from particle.manifest
# import Particle, ...` etc. from inside the user's bundle.py.
import particle  # noqa: F401
import particle.manifest as user_manifest


# -- user-bundle loader --------------------------------------------------

_USER_MODULE_PATH = "/particle/bundle.py"
_USER_MODULE_DIR = os.path.dirname(_USER_MODULE_PATH)
# Where the build pipeline unpacks resolved wheels. Mounted by the
# host as part of the particle's FS — same wasi:filesystem preopen
# that exposes bundle.py. Adding it to sys.path lets user code do
# `import httpx` (or any other resolved pure-Python dep) at runtime.
_DEPS_SITE_PACKAGES = "/particle/_deps/site-packages"

# Sticky cache so each tool call doesn't reparse/re-exec the bundle.
# Errors stick too: a malformed bundle gets the same error every call
# rather than retrying the broken import.
_user_module: object | None = None
_load_error: BaseException | None = None


def _load_user_module():
    """Load /particle/bundle.py through importlib.SourceFileLoader.

    SourceFileLoader bypasses sys.path entirely (we point it directly
    at the file). We still mutate sys.path so user code doing its own
    `import sibling` works for multi-file particles.
    """
    global _user_module, _load_error
    if _user_module is not None:
        return _user_module
    if _load_error is not None:
        raise _load_error

    try:
        if _USER_MODULE_DIR not in sys.path:
            sys.path.insert(0, _USER_MODULE_DIR)
        # _deps/site-packages contains the build-pipeline-resolved
        # wheels (httpx, pyjwt, …). Only added when the directory
        # actually exists — particles with no third-party deps never
        # ship the _deps tree, and a non-existent sys.path entry is
        # harmless but noise in tracebacks.
        if os.path.isdir(_DEPS_SITE_PACKAGES) and _DEPS_SITE_PACKAGES not in sys.path:
            sys.path.insert(0, _DEPS_SITE_PACKAGES)
        loader = importlib.machinery.SourceFileLoader("bundle", _USER_MODULE_PATH)
        spec = importlib.util.spec_from_loader("bundle", loader)
        if spec is None:
            raise RuntimeError(f"could not build module spec for {_USER_MODULE_PATH}")
        module = importlib.util.module_from_spec(spec)
        loader.exec_module(module)
    except BaseException as e:
        _load_error = e
        raise

    _user_module = module
    return module


def _get_particle() -> user_manifest.Particle:
    """Return the module-level `particle` instance from the user's
    bundle. The user constructs a `particle.manifest.Particle`
    dataclass at module scope; the dataclass shape carries everything
    the runtime needs (tool handlers, ping handler, credential
    declarations, capabilities) in typed form.
    """
    mod = _load_user_module()
    obj = getattr(mod, "particle", None)
    if obj is None:
        raise RuntimeError(
            "bundle.py must define a module-level `particle = Particle(...)` "
            "(import Particle from `particle.manifest`)"
        )
    if not isinstance(obj, user_manifest.Particle):
        raise RuntimeError(
            f"bundle.py `particle` must be a particle.manifest.Particle, "
            f"got {type(obj).__name__}"
        )
    return obj


def _describe(e: BaseException) -> str:
    """One-line summary for the WIT `error-detail.message` field —
    user-visible, deliberately short."""
    msg = str(e) or repr(e)
    return f"{type(e).__name__}: {msg}"


def _format_stack(e: BaseException) -> str:
    """Full Python traceback for the WIT `error-detail.stack` field —
    operator-visible; the host typically routes it to a log line
    rather than the user-facing error."""
    return "".join(traceback.format_exception(type(e), e, e.__traceback__))


def _tool_detail(e: BaseException) -> ToolErrorDetail:
    return ToolErrorDetail(message=_describe(e), stack=_format_stack(e))


def _health_detail(e: BaseException) -> HealthErrorDetail:
    return HealthErrorDetail(message=_describe(e), stack=_format_stack(e))


def _manifest_detail(e: BaseException) -> ManifestErrorDetail:
    return ManifestErrorDetail(message=_describe(e), stack=_format_stack(e))


def _log_traceback(e: BaseException) -> None:
    """Mirror the stack to wasi:cli/stderr in addition to attaching
    it to the WIT error. Belt-and-suspenders: some throw paths (e.g.,
    module-evaluation traps) never reach a WIT return, only stderr
    survives those.
    """
    traceback.print_exception(type(e), e, e.__traceback__, file=sys.stderr)


# -- WIT exports ---------------------------------------------------------


class Tools(ToolsProtocol):
    """Implements `particle:runtime/tools`."""

    def list_tools(self) -> list[ToolDef]:
        try:
            p = _get_particle()
        except BaseException as e:
            _log_traceback(e)
            # list-tools has no error variant — surface the load
            # failure as a recognizable tool row so the host gets a
            # readable diagnostic rather than a wasm trap.
            return [ToolDef(
                name="__particle_load_error__",
                description=_describe(e),
                input_schema_json="{}",
            )]

        out: list[ToolDef] = []
        for name, tool in p.tools.items():
            out.append(ToolDef(
                name=name,
                description=tool.description,
                input_schema_json=json.dumps(tool.input_schema),
            ))
        return out

    def call_tool(self, name: str, arguments_json: str) -> str:
        try:
            p = _get_particle()
        except BaseException as e:
            _log_traceback(e)
            raise Err(ToolError_HandlerError(_tool_detail(e)))

        tool = p.tools.get(name)
        if tool is None:
            raise Err(ToolError_NotFound())

        if not callable(tool.handler):
            raise Err(ToolError_HandlerError(ToolErrorDetail(
                message=f"tool {name!r} has no callable handler",
                stack=None,
            )))

        # Args are pre-validated host-side against the tool's input
        # schema (design doc §6 "Argument validation: host-side
        # only"). Trust them.
        try:
            args = json.loads(arguments_json)
        except Exception as e:
            raise Err(ToolError_HandlerError(ToolErrorDetail(
                message=f"argument JSON parse: {_describe(e)}",
                stack=_format_stack(e),
            )))

        try:
            result = tool.handler(args)
            if asyncio.iscoroutine(result):
                result = asyncio.run(result)
        except BaseException as e:
            _log_traceback(e)
            raise Err(ToolError_HandlerError(_tool_detail(e)))

        try:
            return json.dumps(result)
        except Exception as e:
            raise Err(ToolError_HandlerError(ToolErrorDetail(
                message=f"result is not JSON-serializable: {_describe(e)}",
                stack=_format_stack(e),
            )))


class Manifest(ManifestProtocol):
    """Implements `particle:runtime/manifest` — see the WIT for rationale.

    Called by the build pipeline (Phase 5) and by any host that wants
    to learn what credentials/tools the particle exposes. Module-
    scope `particle.*` helper calls aren't supported: under introspect
    the host wires trap stores so those surface as "not allowed
    during get-manifest" errors.
    """

    def get_manifest(self) -> ParticleManifest:
        try:
            p = _get_particle()
        except BaseException as e:
            _log_traceback(e)
            raise Err(ManifestError_BundleLoadError(_manifest_detail(e)))

        try:
            return _build_manifest_record(p)
        except BaseException as e:
            _log_traceback(e)
            raise Err(ManifestError_InvalidManifest(_manifest_detail(e)))


# Lookup tables mapping the user-facing string-literal values to the
# WIT-generated enum cases. Defined once so the conversion functions
# stay declarative.

_OAUTH2_FLOW_MAP = {
    "authorization-code":      Oauth2Flow.AUTHORIZATION_CODE,
    "authorization-code-pkce": Oauth2Flow.AUTHORIZATION_CODE_PKCE,
    "device-code":             Oauth2Flow.DEVICE_CODE,
}
_APIKEY_LOCATION_KIND_MAP = {
    "header":      ApikeyLocationKind.HEADER,
    "auth-scheme": ApikeyLocationKind.AUTH_SCHEME,
    "query-param": ApikeyLocationKind.QUERY_PARAM,
}
_SIGNING_ALGORITHM_MAP = {
    "hmac-sha256": SigningAlgorithm.HMAC_SHA256,
    "hmac-sha512": SigningAlgorithm.HMAC_SHA512,
}


def _build_manifest_record(p: user_manifest.Particle) -> ParticleManifest:
    """Lift the user-facing `Particle` dataclass into the WIT
    `ParticleManifest` record — a tree of componentize-py dataclass
    instances the WIT canonical ABI knows how to send across the host
    boundary. Type validation is handled by the user-facing dataclass
    constructors; this function only re-shapes.
    """
    if p.http is None:
        capabilities = CapabilitySet(http=None)
    else:
        capabilities = CapabilitySet(
            http=HttpCapability(allowed_hosts=list(p.http.allowed_hosts)),
        )

    return ParticleManifest(
        name=p.name,
        description=p.description,
        version=p.version,
        capabilities=capabilities,
        credentials=[_to_credential_entry(name, cred) for name, cred in p.credentials.items()],
        tools=[_to_tool_entry(name, tool) for name, tool in p.tools.items()],
    )


def _to_credential_entry(cname: str, cred: user_manifest.Credential) -> CredentialEntry:
    return CredentialEntry(
        name=cname,
        hosts=list(cred.hosts),
        required=cred.required,
        methods=[
            CredentialMethodEntry(
                name=mname,
                description=getattr(method, "description", "") or "",
                method=_to_credential_method(cname, mname, method),
            )
            for mname, method in cred.methods.items()
        ],
    )


def _to_credential_method(cname: str, mname: str, method) -> "CredentialMethod":
    """Map a user-facing method instance to the WIT variant case. The
    type discriminator is the Python class itself — no `type:` string
    needed, the dataclass identity carries the meaning."""
    if isinstance(method, user_manifest.Basic):
        return CredentialMethod_Basic()
    if isinstance(method, user_manifest.Raw):
        return CredentialMethod_Raw()
    if isinstance(method, user_manifest.OAuth2):
        try:
            mapped_flows = [_OAUTH2_FLOW_MAP[f] for f in method.flows]
        except KeyError as e:
            raise ValueError(
                f"credentials.{cname}.methods.{mname}: unknown OAuth2 flow {e}"
            )
        return CredentialMethod_Oauth2(value=Oauth2Method(
            flows=mapped_flows,
            scopes=list(method.scopes),
            authorization_url=method.authorization_url,
            token_url=method.token_url,
            device_auth_url=method.device_auth_url,
        ))
    if isinstance(method, user_manifest.ApiKey):
        loc = method.location
        if loc is None:
            return CredentialMethod_Apikey(value=ApikeyMethod(location=None))
        try:
            kind_enum = _APIKEY_LOCATION_KIND_MAP[loc.kind]
        except KeyError:
            raise ValueError(
                f"credentials.{cname}.methods.{mname}.location.kind "
                f"{loc.kind!r} not recognized"
            )
        return CredentialMethod_Apikey(value=ApikeyMethod(location=ApikeyLocation(
            kind=kind_enum,
            name=loc.name,
            scheme=loc.scheme,
        )))
    if isinstance(method, user_manifest.SigningKey):
        try:
            alg = _SIGNING_ALGORITHM_MAP[method.algorithm]
        except KeyError:
            raise ValueError(
                f"credentials.{cname}.methods.{mname}.algorithm "
                f"{method.algorithm!r} not recognized"
            )
        return CredentialMethod_SigningKey(value=SigningKeyMethod(algorithm=alg))
    raise ValueError(
        f"credentials.{cname}.methods.{mname}: unsupported method type "
        f"{type(method).__name__} — use one of Basic, OAuth2, ApiKey, "
        f"SigningKey, Raw from particle.manifest"
    )


def _to_tool_entry(tname: str, tool: user_manifest.Tool) -> ToolEntry:
    return ToolEntry(
        name=tname,
        description=tool.description,
        input_schema_json=json.dumps(tool.input_schema),
    )


class Health(HealthProtocol):
    """Implements `particle:runtime/health`."""

    def ping(self) -> PingResult:
        try:
            p = _get_particle()
        except BaseException as e:
            _log_traceback(e)
            raise Err(HealthError_HandlerError(_health_detail(e)))

        ping_fn = p.ping
        if not callable(ping_fn):
            raise Err(HealthError_NotImplemented())

        try:
            result = ping_fn()
            if asyncio.iscoroutine(result):
                result = asyncio.run(result)
        except BaseException as e:
            _log_traceback(e)
            raise Err(HealthError_HandlerError(_health_detail(e)))

        return _to_ping_result(result)


def _to_ping_result(payload: object) -> PingResult:
    """Coerce a user-returned payload into a PingResult.

    Accepts either a PingResult instance or the dict form
    `{"status": "ok|degraded|unhealthy", "message"?: str, "details"?: any}`.
    Dict form lets handlers stay free of WIT-binding imports.
    """
    if isinstance(payload, PingResult):
        return payload
    if not isinstance(payload, dict):
        raise RuntimeError(
            f"ping must return a dict or PingResult, got {type(payload).__name__}"
        )
    status_map = {
        "ok": Status.OK,
        "degraded": Status.DEGRADED,
        "unhealthy": Status.UNHEALTHY,
    }
    status_str = payload.get("status", "ok")
    if status_str not in status_map:
        raise RuntimeError(f"ping returned unknown status {status_str!r}")

    message = payload.get("message")
    details = payload.get("details")
    if details is not None and not isinstance(details, str):
        # Match the WIT contract: details is JSON, encoded as string.
        details = json.dumps(details)
    return PingResult(
        status=status_map[status_str],
        message=message,
        details=details,
    )
