// Generated by build-particle-globals.mjs. DO NOT EDIT.
//
// Type declarations for the `@partite-ai/particle` manifest types
// and the host-provided `@partite-ai/particle-*` modules. The
// typecheck wasm injects this file into every program as a
// synthetic root, so user particles get type-checking on
// `satisfies Particle`, `credentials.fetcher(...)`, `kv.set(...)`,
// etc. without needing to install the npm packages locally.
//
// Source of truth: each module's body comes verbatim from the
// matching published types package under js-types/ (particle/ and
// particle-*/index.d.ts). Re-run this generator (driven by the
// typecheck Makefile target) when those change.


declare module "@partite-ai/particle" {
  /**
   * Type definition for the value a `Particlefile.{ts,js}` default-exports.
   *
   * Use it to get type-checking on your particle definition:
   *
   * ```ts
   * import type { Particle } from "@partite-ai/particle";
   *
   * export default {
   *   name: "yaml-tools",
   *   description: "Parse and format YAML",
   *   version: "0.1.0",
   *   capabilities: {},
   *   tools: {
   *     parse: {
   *       description: "Parse YAML to JSON",
   *       inputSchema: {
   *         type: "object",
   *         properties: { input: { type: "string" } },
   *         required: ["input"],
   *       },
   *       handler: async ({ input }: { input: string }) => ({ result: input }),
   *     },
   *   },
   * } satisfies Particle;
   * ```
   *
   * Schema-derived argument typing is left to the user — JSON Schema doesn't
   * round-trip cleanly through TypeScript's type system. Annotate the handler's
   * parameter explicitly (as above), or cast inside the handler.
   *
   * Spec: docs/initial-design.md §4 (Particlefile DSL).
   */
  
  // -----------------------------------------------------------------------------
  // Top-level
  // -----------------------------------------------------------------------------
  
  /**
   * The default export of a Particlefile.
   */
  export interface Particle {
    /** Particle identifier; kebab-case. Must match `[a-z0-9][a-z0-9-]*`. */
    name: string;
  
    /** One-line human-readable description. Surfaces in `particle ls`, MCP tool listings, etc. */
    description: string;
  
    /** Semver version string (e.g., "0.1.0"). The build pipeline checks this. */
    version: string;
  
    /**
     * Optional. Names the guest engine the runtime should use for this
     * particle. JS/TS particles default to `"js"` if omitted — the only
     * value this field needs in a `Particlefile.ts`. Python particles
     * (`Particlefile.py`) are tagged `"python"` automatically by the
     * build pipeline.
     */
    runtime?: "js" | "python";
  
    /**
     * Declares which host capabilities this particle uses. Importing a
     * `particle:*` namespace whose capability isn't listed here is a build
     * error — every host call is gated by an explicit declaration.
     */
    capabilities: Capabilities;
  
    /**
     * Named credentials the particle needs. Each entry declares one
     * or more alternative methods (the user picks at setup), and
     * optionally pins the credential to a set of HTTP destinations —
     * a credential's value is only substituted into requests bound
     * for one of those hosts.
     *
     * Credentials are NOT a capability: they don't gate runtime
     * behavior, they describe what secret material the particle's
     * declared HTTP allow-list needs. The runtime's
     * `particle:host/credentials` interface is wired unconditionally;
     * this map controls what's stored and how it's applied.
     */
    credentials?: Record<string, CredentialDecl>;
  
    /**
     * Tools the particle exposes. Keys are the tool names that will be
     * surfaced over MCP / `particle run`.
     */
    tools: Record<string, ToolDef>;
  
    /**
     * Optional health-check handler. Called by `particle ping`. Omit if
     * the particle has no meaningful liveness signal — `particle ping`
     * will report "not implemented" and exit 0.
     */
    ping?(): PingResult | Promise<PingResult>;
  
    /**
     * Optional inline test cases run by `particle test`.
     */
    tests?: TestCase[];
  }
  
  // -----------------------------------------------------------------------------
  // Tools
  // -----------------------------------------------------------------------------
  
  export interface ToolDef {
    /** Human-readable description shown to LLM clients. */
    description: string;
  
    /**
     * JSON-Schema (Draft 2020-12) describing the tool's argument object.
     * Must have root `type: "object"`. Validated host-side before the
     * handler runs — invalid arguments never reach this function.
     */
    inputSchema: JSONSchema;
  
    /**
     * The tool body. Receives the validated argument object; returns
     * any JSON-serializable value (or a Promise of one). Throwing
     * surfaces to the caller as a handler error.
     *
     * Note: this is declared with method-shorthand syntax so user
     * handlers can type their argument explicitly
     * (e.g., `handler: ({ input }: { input: string }) => …`)
     * without TypeScript flagging a contravariance error against
     * `args: unknown`.
     */
    handler(args: unknown): unknown | Promise<unknown>;
  }
  
  /**
   * A subset of JSON Schema — just enough structure to constrain the
   * shape of `inputSchema` without trying to model every keyword.
   * Unrecognized keywords are allowed (the host validates against the
   * full draft).
   */
  export interface JSONSchema {
    type?: "object" | "string" | "number" | "integer" | "boolean" | "array" | "null";
    properties?: Record<string, JSONSchema>;
    required?: string[];
    items?: JSONSchema | JSONSchema[];
    enum?: unknown[];
    description?: string;
    default?: unknown;
    // The 2020-12 draft has many more keywords (oneOf, anyOf, allOf,
    // const, format, …). They're permitted here via the index
    // signature so the type doesn't fight users who reach for them.
    [keyword: string]: unknown;
  }
  
  // -----------------------------------------------------------------------------
  // Health
  // -----------------------------------------------------------------------------
  
  export interface PingResult {
    status: "ok" | "degraded" | "unhealthy";
    message?: string;
    details?: string;
  }
  
  // -----------------------------------------------------------------------------
  // Tests
  // -----------------------------------------------------------------------------
  
  export interface TestCase {
    /** Test name shown in `particle test` output. */
    name: string;
    /** Tool to invoke. Must match a key in `tools`. */
    tool: string;
    /** Arguments passed to the handler. Validated against the tool's `inputSchema`. */
    args: unknown;
    /** Expected handler return value. Compared deep-equal. */
    expect?: unknown;
    /** Or, expect the handler to error. */
    expectError?: {
      kind: "handler-error" | "invalid-arguments" | "capability-denied" | "not-found";
      messageMatches?: string;
    };
  }
  
  // -----------------------------------------------------------------------------
  // Capabilities
  // -----------------------------------------------------------------------------
  
  export interface Capabilities {
    /**
     * Outbound HTTP. The host's policy denies every request whose
     * URL hostname isn't in `allowedHosts`. Omitting `http` (or
     * leaving `allowedHosts` empty) denies everything.
     */
    http?: HTTPCapability;
  
    /**
     * Host filesystem access. Declares named mounts (host
     * directories the user maps in at install / run time) and temp
     * mounts (scratch space the host provisions fresh each run).
     * Omitting `filesystem` grants no filesystem access beyond the
     * particle's own bundle.
     */
    filesystem?: FilesystemCapability;
  
    /**
     * Per-particle key/value storage. Set to `{ enabled: true }` to
     * use `@partite-ai/particle-kv`. Omitting `kv` (or setting
     * `enabled: false`) leaves the runtime's kv adapter in
     * denied-trap mode — every kv call surfaces a `not-declared`
     * error. No user approval is required at install; the manifest
     * declaration is the sole gate.
     */
    kv?: KVCapability;
  }
  
  export interface KVCapability {
    /**
     * Turns the per-particle KV store on. The shape is a record
     * rather than a bare boolean so future knobs (quota, namespace)
     * can be added without a schema break.
     */
    enabled: boolean;
  }
  
  export interface HTTPCapability {
    /**
     * Hosts the particle is permitted to reach. Wildcards aren't
     * supported in v1; list each host literally.
     */
    allowedHosts?: string[];
  }
  
  // -----------------------------------------------------------------------------
  // Filesystem
  //
  // Mounts and temp mounts are keyed by a stable mount *name* — the
  // identifier the `particle mount <particle> <name> <host-path>`
  // command and the `--mount name=path` run flag refer to. The handler
  // opens files at the declared `path`; the name itself never appears
  // inside the sandbox.
  //
  // From a UX standpoint the user mapping a directory cares about the
  // name and description, not the path — so lead with those. The path
  // is an implementation detail the author picks and the handler reads.
  // -----------------------------------------------------------------------------
  
  export interface FilesystemCapability {
    /**
     * Host directories the particle reads (and, when `access` is
     * `"readwrite"`, writes). Each is mapped to a real directory by
     * the user — persistently via `particle mount`, or per-run via
     * `--mount name=path`. A `required` mount must be mapped before
     * the particle will run (enforced at run time, not install).
     */
    mounts?: Record<string, MountDecl>;
  
    /**
     * Scratch areas the host provisions automatically: a fresh empty
     * directory each run, capped at `maxSize`, cleared when the
     * particle exits. Always read-write; the user never maps these.
     */
    temp?: Record<string, TempMountDecl>;
  }
  
  export interface MountDecl {
    /**
     * Human-readable explanation of what this mount is for. Shown in
     * the install permission prompt and `particle mount` listings.
     */
    description: string;
  
    /**
     * Absolute path the mount appears at inside the sandbox. The
     * handler opens files here (e.g. `/data/report.json`).
     */
    path: string;
  
    /**
     * `"readonly"` exposes the directory for reading only; the
     * runtime rejects writes. `"readwrite"` permits create / write /
     * delete within the mount.
     */
    access: "readonly" | "readwrite";
  
    /**
     * Refuse to run the particle until the user maps a host
     * directory for this mount. Defaults to `false`. Does NOT block
     * install — a required mount left unmapped fails at run time.
     */
    required?: boolean;
  }
  
  export interface TempMountDecl {
    /**
     * Human-readable explanation of what the scratch space is for.
     * Shown in the install permission prompt.
     */
    description: string;
  
    /** Absolute path the scratch directory appears at inside the sandbox. */
    path: string;
  
    /**
     * Maximum total file-content bytes. A bare integer is bytes; a
     * unit suffix multiplies by 1024ⁿ — `"10000"` is 10000 bytes,
     * `"10KB"` is 10240, and `"MB"` / `"GB"` scale further. Writes
     * that would exceed it fail. Required.
     */
    maxSize: string;
  }
  
  // -----------------------------------------------------------------------------
  // Credentials
  //
  // One entry per named credential the particle uses (e.g., "github",
  // "openai"). Each declares one or more alternative authentication
  // methods — at setup the user picks one and only that one is
  // provisioned. The runtime exposes the chosen method's name via
  // `credentials.getConfiguredMethod(name)`.
  //
  // `hosts` is the HTTP-side binding: when set, the host-side
  // substitution policy only swaps the credential's placeholder for
  // the real value on requests whose hostname is in `hosts`. Omit
  // for non-HTTP credentials (e.g., signing keys), where the
  // credential is accessed by name through the relevant host
  // interface and HTTP scoping is irrelevant.
  //
  // Each method declaration is one of the five typed variants,
  // discriminated on `type` — TypeScript narrows correctly when the
  // user reads `m.type === "oauth2"` etc.
  // -----------------------------------------------------------------------------
  
  export interface CredentialDecl {
    /**
     * Hosts on which the host-side wasi:http policy is allowed to
     * substitute this credential. Exact match against the request
     * URL's hostname; wildcards aren't supported. Every entry must
     * also appear in `capabilities.http.allowedHosts` — the build
     * pipeline rejects out-of-scope hosts.
     *
     * Absent → not bound to any HTTP destination. Use for
     * credentials consumed entirely via the JS-side API (signing
     * keys, raw values) where HTTP substitution isn't relevant.
     */
    hosts?: string[];
  
    /**
     * Refuse to register the particle until one method for this
     * credential is configured. Defaults to `false` — handlers
     * should treat `credentials.getConfiguredMethod(name)`
     * returning `null` as the unauthenticated state.
     */
    required?: boolean;
  
    /**
     * Alternative authentication methods. The user picks one at
     * setup; the rest are never touched. A single entry skips the
     * prompt.
     */
    methods: Record<string, CredentialMethod>;
  }
  
  export type CredentialMethod =
    | BasicCredentialMethod
    | OAuth2CredentialMethod
    | APIKeyCredentialMethod
    | SigningKeyCredentialMethod
    | RawCredentialMethod;
  
  interface CredentialMethodBase {
    /** Human-readable description shown during `particle setup`. */
    description?: string;
  }
  
  export interface BasicCredentialMethod extends CredentialMethodBase {
    type: "basic";
  }
  
  export interface OAuth2CredentialMethod extends CredentialMethodBase {
    type: "oauth2";
    /**
     * OAuth flows the particle supports. `particle setup` lets the
     * user pick when more than one is offered. Listing a single
     * value fixes the flow without prompting.
     */
    flows: OAuth2Flow[];
    /** Application-level scope set this credential is granted. */
    scopes: string[];
  
    /**
     * Pre-set authorization endpoint. Set to skip the prompt;
     * empty / unset → setup prompts with no default.
     */
    authorizationUrl?: string;
    /** Pre-set token endpoint. Same prompt-vs-hardcoded behavior. */
    tokenUrl?: string;
    /** Pre-set device-authorization endpoint (used by `device-code` flow). */
    deviceAuthUrl?: string;
  }
  
  export type OAuth2Flow =
    /** Browser-based; PKCE-only client (typically no client secret). */
    | "authorization-code-pkce"
    /** Browser-based; client-secret-bearing OAuth app. */
    | "authorization-code"
    /** Headless / SSH-friendly; user authorizes on a separate device. */
    | "device-code";
  
  export interface APIKeyCredentialMethod extends CredentialMethodBase {
    type: "apikey";
    /**
     * Optional pre-set location. When provided, setup skips the
     * "where does this key appear?" prompt and only asks for the
     * key value. Useful when the API has a single canonical place
     * for its key — e.g., GitHub PATs always go in
     * `Authorization: Bearer <pat>`.
     */
    location?: APIKeyApplyLocation;
  }
  
  /**
   * Where an apikey credential's value gets substituted in an
   * outgoing HTTP request. The kind discriminator keys the rest of
   * the shape — TypeScript narrows correctly when you switch on it.
   */
  export type APIKeyApplyLocation =
    /** `<name>: <key>` — a custom request header. */
    | { kind: "header"; name: string }
    /** `Authorization: <scheme> <key>` — e.g. "Bearer", "Token". */
    | { kind: "auth-scheme"; scheme: string }
    /** `?<name>=<key>` — appended to the URL query string. */
    | { kind: "query-param"; name: string };
  
  export interface SigningKeyCredentialMethod extends CredentialMethodBase {
    type: "signing-key";
    /** v1 supports HMAC-SHA-256 and HMAC-SHA-512. */
    algorithm: "hmac-sha256" | "hmac-sha512";
  }
  
  export interface RawCredentialMethod extends CredentialMethodBase {
    type: "raw";
    // Setup shows an explicit warning before storing — `raw`
    // credentials are returned in plaintext to the JS handler.
  }
}

declare module "@partite-ai/particle-credentials" {
  // TypeScript types for the host-provided `@partite-ai/particle-credentials`
  // module. The runtime resolves this import to a JS shim that wraps the
  // WIT-imported `particle:host/credentials@0.1.0` interface — see the
  // Particle repository for the implementation. This npm package ships
  // types only; the actual implementation is provided by the Particle
  // runtime at execution time.
  
  /**
   * Per-particle credential access. The particle's top-level
   * `credentials` map declares which names are valid — calling
   * `fetcher` / `getRaw` with an undeclared name throws a
   * `not-configured` error.
   */
  export const credentials: {
    /**
     * Returns a fetch-shaped function bound to the named credential.
     * Each request through it receives the credential at the
     * configured location (Authorization header, custom header, or
     * query param) before the request leaves the host.
     *
     * Host-side scope: when the manifest pins the credential to a
     * `hosts` set, substitution only fires on requests to one of
     * those hosts; a stray request to another host transmits the
     * placeholder literally and the upstream returns 401, surfacing
     * misuse to the particle.
     *
     * Available for `basic`, `oauth2`, and `apikey` credentials. For
     * `signing-key` / `raw`, use `@partite-ai/particle-signing`'s
     * `signing.sign` or this module's `getRaw` instead — calling
     * `fetcher` on those throws `type-mismatch`.
     */
    fetcher(name: string): Promise<(input: string | URL, init?: RequestInit) => Promise<Response>>;
  
    /**
     * Returns the raw value of a `raw`-typed credential. Importing
     * this function requires at least one `type: "raw"` credential
     * in the manifest — making raw access auditable in code review.
     */
    getRaw(name: string): Promise<string>;
  
    /**
     * Lower-level escape hatch: returns an opaque placeholder string
     * + apply-spec for the named credential. Use this when handing a
     * bearer token (or API key) to an SDK that owns its own HTTP
     * client — the SDK can plant the placeholder anywhere it would
     * normally plant the secret, and the host substitutes the real
     * value at the wasi:http boundary as long as the request goes
     * through the global `fetch`.
     *
     * Prefer `fetcher` for the common case (one fetch call, one
     * credential). Reach for `getPlaceholder` when integrating with
     * googleapis, axios, etc.
     *
     * Synchronous — the placeholder is fixed for the particle
     * instance's lifetime.
     */
    getPlaceholder(name: string): {
      placeholder: string;
      apply: { kind: string; name?: string; scheme?: string };
    };
  
    /**
     * Returns the method name the user configured for the named
     * credential at setup, or `null` when no method is set.
     * Particles whose manifest declares multiple alternative
     * methods for a credential (e.g. oauth2 + apikey for the same
     * provider) call this to discover which method backs the
     * credential — usually unneeded if all methods share an
     * apply-spec (the common case).
     *
     * Synchronous — the result is fixed at setup time and resolves
     * via a single host call without any I/O on the hot path.
     */
    getConfiguredMethod(name: string): string | null;
  };
  
  /**
   * Discriminated error thrown from the credentials API. Use a type
   * switch on `tag` to disambiguate.
   */
  export type CredentialError =
    | { tag: "not-configured" }
    | { tag: "not-found" }
    | { tag: "type-mismatch"; val: string }
    | { tag: "storage-error"; val: string };
}

declare module "@partite-ai/particle-oauth" {
  // TypeScript types for the host-provided `@partite-ai/particle-oauth`
  // module. The runtime resolves this import to a JS shim that wraps
  // the WIT-imported `particle:host/oauth@0.1.0` interface — see the
  // Particle repository for the implementation. This npm package
  // ships types only.
  
  /**
   * OAuth-specific operations on top of `@partite-ai/particle-credentials`.
   * Importing this requires at least one `type: "oauth2"` credential
   * in the manifest.
   */
  export const oauth: {
    /**
     * Force a refresh regardless of cached expiry. Use this when an
     * upstream returns 401/403 on a token you thought was still
     * valid; the next `credentials.fetcher` call will pick up the
     * rotated token.
     */
    refresh(name: string): Promise<void>;
  };
  
  export type OAuthError =
    | { tag: "not-configured" }
    | { tag: "not-oauth" }
    | { tag: "refresh-failed"; val: string };
}

declare module "@partite-ai/particle-signing" {
  // TypeScript types for the host-provided `@partite-ai/particle-signing`
  // module. The runtime resolves this import to a JS shim that wraps
  // the WIT-imported `particle:host/signing@0.1.0` interface — see
  // the Particle repository for the implementation. Types only.
  
  /**
   * Cryptographic operations against a host-stored key. The key
   * material never enters JS; sign / verify happen entirely on the
   * host side. Importing this requires at least one
   * `type: "signing-key"` credential in the manifest.
   */
  export const signing: {
    /** Returns the signature of `data` under the named key. */
    sign(name: string, data: Uint8Array): Promise<Uint8Array>;
    /** Returns whether `signature` matches `data` under the named key. */
    verify(name: string, data: Uint8Array, signature: Uint8Array): Promise<boolean>;
  };
  
  export type SigningError =
    | { tag: "not-configured" }
    | { tag: "not-signing-key" }
    | { tag: "invalid-input"; val: string };
}

declare module "@partite-ai/particle-kv" {
  // TypeScript types for the host-provided `@partite-ai/particle-kv`
  // module. The runtime resolves this import to a JS shim that wraps
  // the WIT-imported `particle:host/kv@0.1.0` interface — see the
  // Particle repository for the implementation. Types only.
  
  /**
   * Per-particle key/value store. Strings only — base64-encode
   * binary if you must. Keys and values are scoped by particle name;
   * two particles using the same key see independent values.
   */
  export const kv: {
    /** Returns the stored string, or null if no entry exists. */
    get(key: string): Promise<string | null>;
    /** Replaces or creates the entry. */
    set(key: string, value: string): Promise<void>;
    /** Idempotent — removing an absent key is fine. */
    delete(key: string): Promise<void>;
    /** Returns keys with the given prefix, in unspecified order. */
    list(prefix: string): Promise<string[]>;
  };
  
  export type KVError =
    | { tag: "storage-error"; val: string }
    | { tag: "quota-exceeded" }
    // The particle didn't declare `capabilities.kv` in its manifest.
    // Add `capabilities: { kv: { enabled: true } }` to the default
    // export to enable the store.
    | { tag: "not-declared" };
}
