// Generated by build-particle-globals.mjs. DO NOT EDIT.
//
// Type declarations for the host-provided `@partite-ai/particle-*`
// modules. The typecheck wasm injects this file into every
// program as a synthetic root, so user particles get
// type-checking on `credentials.fetcher(...)`, `kv.set(...)`,
// etc. without needing to install the npm packages locally.
//
// Source of truth: each module's body comes verbatim from the
// matching packages/particle-*/index.d.ts. Re-run this generator
// (driven by the typecheck Makefile target) when those change.


declare module "@partite-ai/particle-credentials" {
  // TypeScript types for the host-provided `@partite-ai/particle-credentials`
  // module. The runtime resolves this import to a JS shim that wraps the
  // WIT-imported `particle:host/credentials@0.1.0` interface — see the
  // Particle repository for the implementation. This npm package ships
  // types only; the actual implementation is provided by the Particle
  // runtime at execution time.
  
  /**
   * Per-particle credential access. The particle's top-level
   * `credentials` map declares which names are valid — calling
   * `fetcher` / `getRaw` with an undeclared name throws a
   * `not-configured` error.
   */
  export const credentials: {
    /**
     * Returns a fetch-shaped function bound to the named credential.
     * Each request through it receives the credential at the
     * configured location (Authorization header, custom header, or
     * query param) before the request leaves the host.
     *
     * Host-side scope: when the manifest pins the credential to a
     * `hosts` set, substitution only fires on requests to one of
     * those hosts; a stray request to another host transmits the
     * placeholder literally and the upstream returns 401, surfacing
     * misuse to the particle.
     *
     * Available for `basic`, `oauth2`, and `apikey` credentials. For
     * `signing-key` / `raw`, use `@partite-ai/particle-signing`'s
     * `signing.sign` or this module's `getRaw` instead — calling
     * `fetcher` on those throws `type-mismatch`.
     */
    fetcher(name: string): Promise<(input: string | URL, init?: RequestInit) => Promise<Response>>;
  
    /**
     * Returns the raw value of a `raw`-typed credential. Importing
     * this function requires at least one `type: "raw"` credential
     * in the manifest — making raw access auditable in code review.
     */
    getRaw(name: string): Promise<string>;
  
    /**
     * Returns the method name the user configured for the named
     * credential at setup, or `null` when no method is set.
     * Particles whose manifest declares multiple alternative
     * methods for a credential (e.g. oauth2 + apikey for the same
     * provider) call this to discover which method backs the
     * credential — usually unneeded if all methods share an
     * apply-spec (the common case).
     *
     * Synchronous — the result is fixed at setup time and resolves
     * via a single host call without any I/O on the hot path.
     */
    getConfiguredMethod(name: string): string | null;
  };
  
  /**
   * Discriminated error thrown from the credentials API. Use a type
   * switch on `tag` to disambiguate.
   */
  export type CredentialError =
    | { tag: "not-configured" }
    | { tag: "not-found" }
    | { tag: "type-mismatch"; val: string }
    | { tag: "storage-error"; val: string };
}

declare module "@partite-ai/particle-oauth" {
  // TypeScript types for the host-provided `@partite-ai/particle-oauth`
  // module. The runtime resolves this import to a JS shim that wraps
  // the WIT-imported `particle:host/oauth@0.1.0` interface — see the
  // Particle repository for the implementation. This npm package
  // ships types only.
  
  /**
   * OAuth-specific operations on top of `@partite-ai/particle-credentials`.
   * Importing this requires at least one `type: "oauth2"` credential
   * in the manifest.
   */
  export const oauth: {
    /**
     * Force a refresh regardless of cached expiry. Use this when an
     * upstream returns 401/403 on a token you thought was still
     * valid; the next `credentials.fetcher` call will pick up the
     * rotated token.
     */
    refresh(name: string): Promise<void>;
  };
  
  export type OAuthError =
    | { tag: "not-configured" }
    | { tag: "not-oauth" }
    | { tag: "refresh-failed"; val: string };
}

declare module "@partite-ai/particle-signing" {
  // TypeScript types for the host-provided `@partite-ai/particle-signing`
  // module. The runtime resolves this import to a JS shim that wraps
  // the WIT-imported `particle:host/signing@0.1.0` interface — see
  // the Particle repository for the implementation. Types only.
  
  /**
   * Cryptographic operations against a host-stored key. The key
   * material never enters JS; sign / verify happen entirely on the
   * host side. Importing this requires at least one
   * `type: "signing-key"` credential in the manifest.
   */
  export const signing: {
    /** Returns the signature of `data` under the named key. */
    sign(name: string, data: Uint8Array): Promise<Uint8Array>;
    /** Returns whether `signature` matches `data` under the named key. */
    verify(name: string, data: Uint8Array, signature: Uint8Array): Promise<boolean>;
  };
  
  export type SigningError =
    | { tag: "not-configured" }
    | { tag: "not-signing-key" }
    | { tag: "invalid-input"; val: string };
}

declare module "@partite-ai/particle-kv" {
  // TypeScript types for the host-provided `@partite-ai/particle-kv`
  // module. The runtime resolves this import to a JS shim that wraps
  // the WIT-imported `particle:host/kv@0.1.0` interface — see the
  // Particle repository for the implementation. Types only.
  
  /**
   * Per-particle key/value store. Strings only — base64-encode
   * binary if you must. Keys and values are scoped by particle name;
   * two particles using the same key see independent values.
   */
  export const kv: {
    /** Returns the stored string, or null if no entry exists. */
    get(key: string): Promise<string | null>;
    /** Replaces or creates the entry. */
    set(key: string, value: string): Promise<void>;
    /** Idempotent — removing an absent key is fine. */
    delete(key: string): Promise<void>;
    /** Returns keys with the given prefix, in unspecified order. */
    list(prefix: string): Promise<string[]>;
  };
  
  export type KVError =
    | { tag: "storage-error"; val: string }
    | { tag: "quota-exceeded" };
}
